# Generated by Django 4.2 on 2023-05-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp_userprofile', '0002_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='contact',
            new_name='user2',
        ),
    ]
