# Generated by Django 4.2 on 2023-05-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp_userprofile', '0003_rename_user_contacts_user1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='status',
            new_name='user1_status',
        ),
        migrations.AddField(
            model_name='contacts',
            name='user2_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('B', 'Blocked')], default='P', max_length=1),
        ),
    ]
